version: '2.0'
services:
  couchdb:
    image: apache/couchdb:latest
    ports:
      - 5984:5984
    environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=admin'

  couchdb-setup:
    build: ./couchdb-setup
    depends_on:
      - couchdb

  couchdb-worker:
    build: ./couchdb-worker
    depends_on:
      - couchdb-setup
    volumes:
      - git-data:/var/www/git

  git-server:
    build: ./git-server
    depends_on:
      - couchdb-worker
    volumes:
      - git-data:/var/www/git
    ports:
      - 8080:80

volumes:
  git-data:
